-- Onyx: the default exercise library no longer lives here.
--
-- It moved into supabase/migrations/0012_exercise_library.sql, which is now its
-- one authoritative copy. That migration is idempotent, so it is safe to run on
-- a database that already holds some defaults, and keeping a second list here
-- would only create something that can drift.
--
-- This file is kept rather than deleted because the setup docs and the repo's
-- shape both refer to it, and an empty file with an explanation is clearer than
-- a missing one.
